CREATE DATABASE IF NOT EXISTS caloriedb;

USE caloriedb;

CREATE TABLE IF NOT EXISTS user (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS meal (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255),
    category VARCHAR(100),
    calories INT,
    date DATE,
    user_id BIGINT,
    FOREIGN KEY (user_id) REFERENCES user(id)
);
